// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSAIv-X1q2G7tqK7KenSv6xPYAIf0pBEU',
    appId: '1:885960821713:web:6f3a35abc68b50b977aef0',
    messagingSenderId: '885960821713',
    projectId: 'logiology-admin',
    authDomain: 'logiology-admin.firebaseapp.com',
    storageBucket: 'logiology-admin.firebasestorage.app',
    measurementId: 'G-NV6FSZ26C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr-4_Fvv3uvCmLM7YNCtO96nobHVY7s7U',
    appId: '1:885960821713:android:d3a4812f9fda362e77aef0',
    messagingSenderId: '885960821713',
    projectId: 'logiology-admin',
    storageBucket: 'logiology-admin.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSAIv-X1q2G7tqK7KenSv6xPYAIf0pBEU',
    appId: '1:885960821713:web:a1100526476b37e677aef0',
    messagingSenderId: '885960821713',
    projectId: 'logiology-admin',
    authDomain: 'logiology-admin.firebaseapp.com',
    storageBucket: 'logiology-admin.firebasestorage.app',
    measurementId: 'G-968Q2Q4SD1',
  );
}
